name: amedspor_app
description: A new Flutter project
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^17.2.3
  firebase_core: ^4.7.0
  firebase_auth: ^6.4.0
  cloud_firestore: ^6.3.0
  cloud_functions: ^6.3.0
  firebase_storage: ^13.3.0
  firebase_messaging: ^16.2.0
  uuid: ^4.5.3
  image_picker: ^1.2.2
  shared_preferences: ^2.5.5
  connectivity_plus: ^7.1.1
  package_info_plus: ^10.1.0
  firebase_analytics: ^12.3.0
  firebase_crashlytics: ^5.2.0
  url_launcher: ^6.3.1
  equatable: ^2.0.7
  intl: ^0.20.2
  flutter_riverpod: ^2.6.1
  cached_network_image: ^3.4.1
  audioplayers: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.9

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#0E0E0E"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/sounds/
  
  # Optimize build for faster startup
  generate: true
  # Fontler için (varsa)
  # fonts:
  #   - family: Inter
  #     fonts:
  #       - asset: assets/fonts/Inter-Regular.ttf
