// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAX5yUdNxyYTSnFYbwl0eXpYcfgVqpxZRQ',
    appId: '1:346583132476:web:5f9066f1ef53a97de41639',
    messagingSenderId: '346583132476',
    projectId: 'amedsporapp',
    authDomain: 'amedsporapp.firebaseapp.com',
    storageBucket: 'amedsporapp.firebasestorage.app',
    measurementId: 'G-MPZ4J15WH1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhDp4hauleQAPk_O9uxM8NJHvnN0IKv5A',
    appId: '1:346583132476:android:c5667c4cf5db9aa9e41639',
    messagingSenderId: '346583132476',
    projectId: 'amedsporapp',
    storageBucket: 'amedsporapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbjYQkFJ5VM2OZz8v9sFoaAHQqoGWLoiY',
    appId: '1:346583132476:ios:679366f352c6e049e41639',
    messagingSenderId: '346583132476',
    projectId: 'amedsporapp',
    storageBucket: 'amedsporapp.firebasestorage.app',
    iosClientId: '346583132476-4nesf78d4at7t8psmdn7s69oj6bbne73.apps.googleusercontent.com',
    iosBundleId: 'com.example.amedsporApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbjYQkFJ5VM2OZz8v9sFoaAHQqoGWLoiY',
    appId: '1:346583132476:ios:679366f352c6e049e41639',
    messagingSenderId: '346583132476',
    projectId: 'amedsporapp',
    storageBucket: 'amedsporapp.firebasestorage.app',
    iosClientId: '346583132476-4nesf78d4at7t8psmdn7s69oj6bbne73.apps.googleusercontent.com',
    iosBundleId: 'com.example.amedsporApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAX5yUdNxyYTSnFYbwl0eXpYcfgVqpxZRQ',
    appId: '1:346583132476:web:ac383801cdbdf4f6e41639',
    messagingSenderId: '346583132476',
    projectId: 'amedsporapp',
    authDomain: 'amedsporapp.firebaseapp.com',
    storageBucket: 'amedsporapp.firebasestorage.app',
    measurementId: 'G-XFX2FR04SD',
  );

}