type User @table {
  username: String!
  email: String!
  createdAt: Timestamp!
  displayName: String
  bio: String
  profilePictureUrl: String
  preferredSports: [String]
  skillLevels: [String]
}

type Sport @table {
  name: String!
  description: String
  iconUrl: String
}

type Team @table {
  name: String!
  sport: Sport!
  createdAt: Timestamp!
  captain: User!
  description: String
  teamPictureUrl: String
}

type TeamMembership @table(key: ["user", "team"]) {
  user: User!
  team: Team!
  role: String!
  joinedAt: Timestamp!
}

type GameEvent @table {
  title: String!
  sport: Sport!
  location: String!
  dateTime: Timestamp!
  maxPlayers: Int!
  createdAt: Timestamp!
  organizer: User!
  description: String
  minPlayers: Int
  isPublic: Boolean
}

type GameParticipant @table(key: ["user", "gameEvent"]) {
  user: User!
  gameEvent: GameEvent!
  joinedAt: Timestamp!
  role: String
  confirmed: Boolean
}

type Post @table {
  content: String!
  createdAt: Timestamp!
  author: User!
  imageUrl: String
  videoUrl: String
  location: String
  associatedSport: Sport
}